DEBUG = True

CONNECTION_STRING = "mongodb://localhost"
DATABASE = "office_gist"

SUPPORT_LANGUAGES = {
    "Text": "text",
    "ActionScript": "asciidoc",
    "C": "c_cpp",
    "C#": "csharp",
    "C++": "c_cpp",
    "Common Lisp": "listp",
    "CSS": "css",
    "Diff": "diff",
    "HTML": "html",
    "Java": "java",
    "JavaScript": "javascript",
    "Lua": "lua",
    "Objective-C": "objectivec",
    "Perl": "perl",
    "PHP": "php",
    "Python": "python",
    "Ruby": "ruby",
    "Scala": "scala",
    "Scheme": "scheme",
    "SQL": "sql",
    "TeX": "tex",
    "XML": "xml",
    "Clojure": "clojure",
    "CoffeeScript": "coffee",
    "ColdFusion": "coldfusion",
    "Dart": "dart",
    "Go": "golang",
    "Groovy": "groovy",
    "Haml": "haml",
    "Haxe": "haxe",
    "HTML+Django": "django",
    "JSON": "json",
    "Makefile": "makefile",
    "Markdown": "markdown",
    "OCaml": "ocaml",
    "R": "r",
    "RHTML": "rhtml",
    "Sass": "sass",
    "Scilab": "scad",
    "SCSS": "scss",
    "Shell": "sh",
    "Tcl": "tcl",
    "Textile": "textile",
    "Visual Basic": "vbscript",
    "XQuery": "xquery",
    "YAML": "yaml",
}
